name: Submodule Update Workflow

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
    - cron: '0 0 * * 3'  # Runs every Wednesday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.DB_PAT }}  # Use the DB_PAT for submodule access

      - name: Create and Update Submodule Branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Fetch the latest changes
          git fetch origin master
          
          # Create or reset the submodule-update-branch to the latest master
          git checkout -B submodule-update-branch origin/master

          # Update submodules
          git submodule update --remote
          
          # Check for changes and commit if there are any
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 1  # Stop the workflow if no changes
          else
            git commit -m "Automated submodule update"
          fi

      - name: Push Changes
        run: |
          git push origin submodule-update-branch --force || echo "Failed to push changes"

      - name: Check for Existing Pull Request
        id: check_pr
        env:
          DB_TOKEN: ${{ secrets.DB_PAT }}
        run: |
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $DB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls)
          
          echo "$response" | jq -r --arg branch "submodule-update-branch" '.[] | select(.head.ref == $branch) | .number' > pr_number.txt
          if [[ -s pr_number.txt ]]; then
            echo "Existing pull request found: $(<pr_number.txt)"
            echo "pr_number=$(<pr_number.txt)" >> $GITHUB_ENV
          else
            echo "No existing pull request found."
          fi

      - name: Create or Update Pull Request
        if: steps.check_pr.outputs.pr_number == ''
        env:
          DB_TOKEN: ${{ secrets.DB_PAT }}
        run: |
          response=$(curl --http1.1 \
            -L \
            -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $DB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"Automated Submodule Update","body":"This pull request updates the submodules to their latest versions.", "head":"submodule-update-branch", "base":"master"}'
          )
          
          echo "$response"

          if [[ $(echo "$response" | jq -r '.id') == "null" ]]; then
            echo "Failed to create pull request."
            exit 1
          fi

      - name: Update Existing Pull Request
        if: steps.check_pr.outputs.pr_number != ''
        env:
          DB_TOKEN: ${{ secrets.DB_PAT }}
          PULL_NUMBER: ${{ steps.check_pr.outputs.pr_number }}
        run: |
          response=$(curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $DB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PULL_NUMBER \
            -d '{"title":"Automated Submodule Update","body":"This pull request updates the submodules to their latest versions.", "state":"open"}'
          )
          
          echo "$response"

          if [[ $(echo "$response" | jq -r '.id') == "null" ]]; then
            echo "Failed to update pull request."
            exit 1
          fi
