name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
    - cron: '0 0 * * 3'  # Runs every Wednesday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Update Submodules
        run: |
          git submodule update --remote
          git diff --exit-code || echo "Submodules updated"

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Automated submodule update" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin HEAD:refs/heads/submodule-update-branch || echo "No changes to push"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE="Automated Submodule Update"
          PR_BODY="This pull request updates the submodules to their latest versions."
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"submodule-update-branch\",\"base\":\"master\"}" \
            https://api.github.com/repos/${{ github.repository }}/pulls
