name: Submodule Update Workflow

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
    - cron: '0 0 * * 3'  # Runs every Wednesday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.DB_PAT }}  # Use the DB_PAT for submodule access

      - name: Update Submodules
        run: |
          git submodule update --remote
          git diff --exit-code || echo "Submodules updated"

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 1  # Stop the workflow if no changes
          else
            git commit -m "Automated submodule update"
          fi

      - name: Push Changes
        run: |
          git fetch origin submodule-update-branch || echo "No remote branch to fetch"
          git checkout submodule-update-branch || git checkout -b submodule-update-branch
          git merge origin/submodule-update-branch || echo "No changes to merge"
          git push origin HEAD:refs/heads/submodule-update-branch || echo "Failed to push changes"


      - name: Create Pull Request
        env:
          DB_TOKEN: ${{ secrets.DB_PAT }}
        run: |
          response=$(curl --http1.1 \
            -L \
            -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $DB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"Automated Submodule Update","body":"This pull request updates the submodules to their latest versions.", "head":"submodule-update-branch", "base":"master"}'
          )
          
          echo "$response"

          if [[ $(echo "$response" | jq -r '.id') == "null" ]]; then
            echo "Failed to create pull request."
            exit 1
          fi
          
